import test from 'node:test';
import assert from 'node:assert/strict';
import {cleanConfig,readHistory,recordResult,summarizeHistory,savePreset,readPresets,deletePreset,clearHistory,HISTORY_KEY} from '../public/guest-data.js';
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}};
test('guest game history records completed games once without secrets',()=>{const s=storage(),config={expansions:['glyphs'],difficulties:{}};assert.equal(recordResult(s,{id:'one',mode:'solo',status:'active',turn:3,config}),false);assert.equal(recordResult(s,{id:'one',mode:'solo',status:'won',turn:13,config}),true);assert.equal(recordResult(s,{id:'one',mode:'solo',status:'lost',turn:14,config}),false);assert.equal(readHistory(s).length,1);assert.equal(s.getItem(HISTORY_KEY).includes('token'),false);assert.equal(summarizeHistory(readHistory(s)).winRate,100);clearHistory(s);assert.equal(readHistory(s).length,0);});
test('guest statistics correctly distinguish modes and statuses',()=>{const s=storage(),config={expansions:[],difficulties:{}};recordResult(s,{id:'x',mode:'solo',status:'lost',turn:4,config});recordResult(s,{id:'y',mode:'coop',status:'won',turn:20,config});recordResult(s,{id:'z',mode:'solo',status:'won',turn:7,config});assert.deepEqual(summarizeHistory(readHistory(s)),{played:3,wins:2,losses:1,winRate:67,solo:2,coop:1,bestWinTurns:7});});
test('saved setups deduplicate by name, can load/delete, and reject unsupported values',()=>{const s=storage();const p=savePreset(s,'  Favorite  ',{expansions:['glyphs','book'],difficulties:{book:'hard'}});assert.equal(readPresets(s)[0].name,'Favorite');const q=savePreset(s,'favorite',{expansions:[],difficulties:{}});assert.equal(q.id,p.id);assert.equal(readPresets(s).length,1);assert.equal(deletePreset(s,p.id),true);assert.equal(readPresets(s).length,0);assert.throws(()=>cleanConfig({expansions:['incubus','glyphs']}),/cannot be combined/);assert.throws(()=>cleanConfig({expansions:['fake']}),/Unknown expansion/);assert.throws(()=>cleanConfig({expansions:['book'],difficulties:{book:'impossible'}}),/difficulty/);});
test('corrupt browser storage does not break history and presets',()=>{const s=storage();s.setItem('onirama.history.v1','{unreadable');s.setItem('onirama.presets.v1','{}');assert.deepEqual(readHistory(s),[]);assert.deepEqual(readPresets(s),[]);});
test('history bounds apply to repeated sessions and no replay secrets are recorded',()=>{const s=storage();for(let i=0;i<215;i++)recordResult(s,{id:`game-${i}`,mode:'solo',status:i%2?'won':'lost',turn:i+1,config:{expansions:[]}});assert.equal(readHistory(s).length,200);assert.equal(readHistory(s)[0].id,'game-214');assert.equal(readHistory(s).at(-1).id,'game-15');});
