import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {newGame,viewFor} from '../engine/game.js';
import * as guest from '../public/guest-data.js';
const source=readFileSync('public/app.js','utf8').replace(/^import .* from '\.\/guest-data\.js';\s*/,'').replace(/^import \* as firebase from '\.\/firebase-room\.js';\s*/m,'');
function setupUI(){const storage=new Map(),app={innerHTML:'',addEventListener(){}},announcer={textContent:''},inputs={};const localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};const location={origin:'http://localhost',hostname:'localhost',hash:'#/'};const document={documentElement:{dataset:{}},querySelector:x=>x==='#app'?app:x==='#sr-announcer'?announcer:inputs[x]||null};const ctx=vm.createContext({document,localStorage,location,addEventListener(){},setTimeout(){},navigator:{},confirm:()=>true,prompt:()=>null,console,...guest,firebase:{firebaseConfigured:()=>false}});vm.runInContext(source,ctx);return {ctx,app,announcer,inputs,localStorage,location};}
test('Phase 8 guest UI: navigation, tutorial, preset setup, history and settings all render',async()=>{const u=setupUI();assert.match(u.app.innerHTML,/Learn to play/);await vm.runInContext('handle("tutorial")',u.ctx);assert.match(u.app.innerHTML,/Guided tutorial/);await vm.runInContext('handle("tutorialNext")',u.ctx);assert.match(u.app.innerHTML,/Your hand/);u.location.hash='#/setup';vm.runInContext('render()',u.ctx);u.inputs['#presetName']={value:'My Setup'};await vm.runInContext('handle("presetSave")',u.ctx);assert.match(u.app.innerHTML,/My Setup/);u.location.hash='#/settings';vm.runInContext('render()',u.ctx);assert.match(u.app.innerHTML,/High contrast/);assert.match(u.app.innerHTML,/Large/);u.location.hash='#/history';vm.runInContext('render()',u.ctx);assert.match(u.app.innerHTML,/No completed games/);});
test('Phase 8 UI renders a finished game and offers local history without exposing deck state',()=>{const u=setupUI();const raw=newGame({seed:456});raw.status='won';raw.phase='ended';const game=JSON.parse(JSON.stringify(viewFor(raw,0)));u.ctx.testGame=game;u.location.hash='#/game';vm.runInContext('state={room:{seat:0,started:true},game:testGame};session={id:"local",seat:0};recordCurrentResult();render();announceCurrent()',u.ctx);assert.match(u.app.innerHTML,/View history/);assert.match(u.announcer.textContent,/Game won/);const history=guest.readHistory(u.localStorage);assert.equal(history.length,1);assert.equal(u.localStorage.getItem(guest.HISTORY_KEY).includes('deck'),false);});
test('malicious or broken local storage is rejected before displaying HTML',()=>{const s=new Map();const storage={getItem:k=>s.get(k)??null,setItem:(k,v)=>s.set(k,v),removeItem:k=>s.delete(k)};s.set('onirama.presets.v1',JSON.stringify([{id:'a" onfocus="evil',name:'Bad',config:{expansions:[]}}]));s.set('onirama.history.v1',JSON.stringify([{id:'a',mode:'solo',status:'won',turn:1,finishedAt:'bad',config:{expansions:['bad']}}]));assert.equal(guest.readPresets(storage).length,0);assert.equal(guest.readHistory(storage).length,0);});
