import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {newGame,act,viewFor,assertConserved} from '../engine/game.js';
import {makeRoom,joinRoom,setReady,updateSetup,startRoom,roomView,playRoom} from '../engine/firebase-protocol.js';
import {renderActionDock,renderPileInspector} from '../public/tabletop/action-dock.js';
import {renderExpansionTabletop} from '../public/tabletop/expansions.js';
import {icon} from '../public/icons.js';
import {renderCard,renderDoors} from '../public/tabletop/cards.js';
import {GUIDE_CHAPTERS,renderRulesReference,renderGuideTutorial,filterGuide} from '../public/rules-guide.js';
import * as guest from '../public/guest-data.js';
const source=readFileSync('public/app.js','utf8').replace(/^import [^\n]+$/gm,'');
function screen(route){const store=new Map(),app={innerHTML:'',addEventListener(){}},location={origin:'https://sea4594.github.io',hostname:'sea4594.github.io',pathname:'/Onirama/',search:'',hash:route};const localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};const document={documentElement:{dataset:{}},querySelector:q=>q==='#app'?app:null};const ctx=vm.createContext({app,location,localStorage,document,window:{},navigator:{},addEventListener(){},console,icon,renderCard,renderDoors,GUIDE_CHAPTERS,renderRulesReference,renderGuideTutorial,filterGuide,...guest,firebase:{firebaseConfigured:()=>true}});vm.runInContext(source,ctx);return {ctx,app,localStorage,location};}
test('menu has separated solo and multiplayer paths, host/join name gates, hotseat setup',()=>{
 const o=screen('#/');assert.match(o.app.innerHTML,/data-action="setup"/);assert.doesNotMatch(o.app.innerHTML,/Choose expansions/);
 o.location.hash='#/setup';vm.runInContext('render()',o.ctx);assert.match(o.app.innerHTML,/Start solo game/);assert.doesNotMatch(o.app.innerHTML,/chooseCoop|id="name"/);
 o.location.hash='#/multiplayer';vm.runInContext('render()',o.ctx);for(const text of ['Online','Hot seat','data-code-index="0"','Host a lobby','Join a lobby','disabled>Join','disabled>Create code'])assert.ok(o.app.innerHTML.includes(text),text);
 vm.runInContext("multiplayerTab='hotseat';render()",o.ctx);assert.match(o.app.innerHTML,/hotseatName1/);assert.match(o.app.innerHTML,/hotseatName2/);assert.match(o.app.innerHTML,/Start game/);assert.match(o.app.innerHTML,/data-expansion="glyphs"/);
});
test('pass-device screen reveals no cards while hiding gameplay',()=>{const o=screen('#/game'),game=viewFor(newGame({mode:'coop',names:['Alex','Sam'],seed:34,manualTurnEnd:true}),0);o.ctx.testGame=game;vm.runInContext('state={room:{seat:0,started:true,hotseat:true,mode:"coop"},game:testGame};session={id:"hotseat",seat:0};passDevice=true;render()',o.ctx);assert.match(o.app.innerHTML,/Pass the device/);assert.match(o.app.innerHTML,/data-action="passReady"/);assert.doesNotMatch(o.app.innerHTML,/data-tabletop-coop|tt6-hand-cards|data-action="draft:/);});
test('new cooperative games may require explicit end-turn and block early moves',()=>{const s=newGame({mode:'coop',seed:123,manualTurnEnd:true});s.phase='turnComplete';s.pending=null;assert.deepEqual(s.players.map(p=>p.hand.length),[0,0]);assert.throws(()=>act(s,{type:'draft',id:s.draft[0].id}),/End this turn/);const next=act(s,{type:'endTurn'});assert.equal(next.phase,'action');assert.equal(next.active,1);assert.ok(renderActionDock(viewFor(s,0),0).includes('data-action="endTurn"'));assert.ok(!renderActionDock(viewFor(s,1),1).includes('data-action="endTurn"'));assertConserved(next);});
test('a normal cooperative action reaches explicit handoff only after refill',()=>{let s=newGame({mode:'coop',seed:2468,manualTurnEnd:true});while(s.phase==='draft')s=act(s,{type:'draft',id:s.draft[0].id});assert.equal(s.active,0);s=act(s,{type:'play',id:s.players[0].hand[0].id});assert.equal(s.phase,'turnComplete');assert.equal(s.active,0);assert.deepEqual(s.players.map(p=>p.hand.length),[3,3]);s=act(s,{type:'endTurn'});assert.equal(s.phase,'action');assert.equal(s.active,1);assert.equal(s.turn,2);assertConserved(s);});
test('spell payment is automatic, removed cards visible separately in discard inspector',()=>{const s=newGame({seed:111,config:{expansions:['book']}});s.discard.push(...s.players[0].hand.splice(0,5),...s.deck.splice(-2));const paid=s.discard.map(c=>c.id);const b=act(s,{type:'cast',spell:'parallel',first:0,second:1});assert.equal(b.discard.length,0);assert.deepEqual(b.moduleState.book.zones.removed.map(c=>c.id),paid);const v=viewFor(b,0),html=renderPileInspector(v,'discard',0);assert.match(html,/Removed from the game/);assert.match(html,/7 cards/);assertConserved(b);});
test('post-action spell remains available before the optional end-turn handoff',()=>{const s=newGame({seed:221,mode:'coop',manualTurnEnd:true,config:{expansions:['book']}});s.phase='turnComplete';s.discard.push(...s.deck.splice(-7));const next=act(s,{type:'cast',spell:'parallel',first:0,second:1});assert.equal(next.phase,'turnComplete');assert.equal(next.active,0);assert.equal(next.moduleState.book.zones.removed.length,7);assertConserved(next);});
test('dreamcatcher area contains four equal tiles and labeled failsafes, not Books',()=>{const g=viewFor(newGame({seed:31,config:{expansions:['dreamcatchers']}}),0),html=renderExpansionTabletop(g);assert.match(html,/Failsafes:/);assert.doesNotMatch(html,/>Books</);assert.equal((html.match(/inspectCatcher:/g)||[]).length,4);const css=readFileSync('public/tabletop/phase13.css','utf8');assert.match(css,/repeat\(4,minmax\(0,1fr\)\)/);});
test('host may change expansion setup before starting; joining player cannot, readiness reset',()=>{let r=makeRoom('ABCD','host','Alex',{expansions:[]});r=joinRoom(r,'guest','Sam');r=setReady(r,'host',true);r=setReady(r,'guest',true);assert.deepEqual(r.ready,[true,true]);assert.throws(()=>updateSetup(r,'guest',{expansions:['glyphs']}),/Only the host/);const changed=updateSetup(r,'host',{expansions:['glyphs']});assert.deepEqual(changed.ready,[false,false]);assert.deepEqual(changed.config.expansions,['glyphs']);assert.throws(()=>startRoom(changed,'host'),/ready/);r=setReady(changed,'host',true);r=setReady(r,'guest',true);r=startRoom(r,'host');assert.equal(r.game.manualTurnEnd,true);assert.throws(()=>updateSetup(r,'host',{expansions:[]}),/locked/);});
