import {icon} from '../public/icons.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {renderCard,renderDoors} from '../public/tabletop/cards.js';
import {applyTabletopMetrics} from '../public/tabletop/layout.js';
import * as guest from '../public/guest-data.js';
import {GUIDE_CHAPTERS,renderRulesReference,renderGuideTutorial,filterGuide} from '../public/rules-guide.js';
const src=readFileSync('public/app.js','utf8').replace(/^import [^\n]+$/gm,'');
function screen(route){const data=new Map(),app={innerHTML:'',addEventListener(){}},location={origin:'https://sea4594.github.io',hostname:'sea4594.github.io',pathname:'/Onirama/',search:'',hash:route};const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const ctx=vm.createContext({app,window:{ONIRAMA_BUILD_COMMIT:'c'.repeat(40)},location,localStorage:storage,document:{documentElement:{dataset:{}},querySelector:q=>q==='#app'?app:null},addEventListener(){},console,icon,navigator:{},renderCard,renderDoors,applyTabletopMetrics,GUIDE_CHAPTERS,renderRulesReference,renderGuideTutorial,filterGuide,...guest,firebase:{firebaseConfigured:()=>true}});vm.runInContext(src,ctx);return {app,ctx,location,storage};}
function go(o,hash){o.location.hash=hash;vm.runInContext('render()',o.ctx);return o.app.innerHTML;}
test('minimal home shows direct actions rather than redundant expansion catalog',()=>{const o=screen('#/');const html=o.app.innerHTML;for(const a of ['soloStart','setup','tutorial','history'])assert.ok(html.includes(`data-action="${a}"`));assert.ok(!html.includes('expansion-row'));assert.ok(!html.includes('The doors are waiting'));assert.ok(!html.includes('Every changing'));});
test('three-tab navigation and join-by-code route remain available',()=>{const o=screen('#/multiplayer');for(const a of ['coopStart','join'])assert.ok(o.app.innerHTML.includes(`data-action="${a}"`));assert.ok(o.app.innerHTML.includes('id="roomcode"'));const html=go(o,'#/join?code=AB12CD34');assert.ok(html.includes('value="AB12CD34"'));assert.ok(html.includes('data-action="join"'));});
test('setup retains every expansion, all difficulty choices, two modes and presets',()=>{const o=screen('#/setup');const html=o.app.innerHTML;for(const id of ['book','glyphs','dreamcatchers','towers','premonitions','crossroads','oniverse','mirrors','sphinx','incubus'])assert.ok(html.includes(`data-expansion="${id}"`),id);assert.ok(html.includes('data-action="chooseSolo"'));assert.ok(html.includes('data-action="chooseCoop"'));assert.ok(html.includes('data-action="presetSave"'));vm.runInContext("selectedExpansions.add('premonitions');selectedExpansions.add('incubus');render()",o.ctx);assert.match(o.app.innerHTML,/Very hard \(6\)/);assert.match(o.app.innerHTML,/True Dreamwalker/);});
test('lobby retains accessible code/link, seat status and readiness with no credentials in invite',()=>{const o=screen('#/game');o.ctx.mockRoom={id:'room',code:'AB12CD34',seat:0,host:true,started:false,connected:[true,true],ready:[true,false]};vm.runInContext('state={room:mockRoom,version:2};session={id:"room",seat:0};render()',o.ctx);const html=o.app.innerHTML;for(const a of ['copyCode','copyInvite','ready','start'])assert.ok(html.includes(`data-action="${a}"`));assert.match(html,/AB12CD34/);assert.ok(html.includes('value="https://sea4594.github.io/Onirama/#/join?code=AB12CD34"'));assert.ok(!html.includes('Bearer '));assert.match(html,/disabled title="Both players must be ready"/);});
test('settings preserve all five preferences, routes, and deployed commit',()=>{const o=screen('#/settings'),html=o.app.innerHTML;for(const key of ['theme','motion','cardSize','contrast','textSize'])assert.match(html,new RegExp(`data-setting="${key}"`));for(const a of ['tutorial','history','rules','testBackend'])assert.ok(html.includes(`data-action="${a}"`));assert.match(html,/github.com\/sea4594\/Onirama\/commit\/cccc/);assert.ok(!html.includes('No player accounts or registration'));});
test('rules reference exposes fully illustrated, searchable chapters',()=>{const html=screen('#/rules').app.innerHTML;assert.equal((html.match(/class="guide-entry"/g)||[]).length,GUIDE_CHAPTERS.reduce((n,c)=>n+c.entries.length,0));assert.match(html,/Nightmares/);assert.match(html,/Three matching colors unlock a Door/);assert.match(html,/Two-player cooperative/);assert.match(html,/data-guide-search/);assert.match(html,/guide-figure/);});
test('history, tutorial and game results entrypoints remain routed',()=>{const o=screen('#/history');assert.match(o.app.innerHTML,/No completed games/);let html=go(o,'#/tutorial');assert.match(html,/Guided tutorial/);vm.runInContext('handle("tutorialNext")',o.ctx);assert.match(o.app.innerHTML,/Your hand/);assert.ok(src.includes('renderSoloTabletop(g,')&&src.includes('renderCooperativeTabletop(g,'));});
test('Pages build includes new stylesheet without hiding existing tabletop styles',()=>{const index=readFileSync('public/index.html','utf8');assert.match(index,/shell\.css/);assert.match(index,/rules-guide\.css/);for(const s of ['tabletop\/solo\.css','tabletop\/coop\.css','tabletop\/dialogs\.css'])assert.ok(index.includes(s));});
